# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4083e2da1d88db234a7207751d27bc911d18e05fadb284139cae120230c8e5e1815e86354f21d34dad2d80a6a93f8f8756e547fd11e403d92386b292fec1a48

test:
  secret_key_base: 6287fcc24e223606d13c917c531482791d352f5aae0cc498165f8d56f5ea1856126d895f31955ed41557c2fc2ab31dc0c2150c0a3b34cfad43927405a351f1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
